### ISSUE TITLE
React-Native app crash - roomSession.audioMute is not a function

### ISSUE THREAD

**Issue by rushirajStl** [signalwire-community/react#19]
Hello,
I have created react native app using https://developer.signalwire.com/guides/video-api/guides/using-video-api-react-native/ link
but I am getting below error, 
roomSession.audioMute is not a function. (In 'roomSession.audioMute()', 'roomSession.audioMute' is undefined)

can anyone help me 
Thanks,
![Screenshot 2022-09-07 at 11 43 57 AM](https://user-images.githubusercontent.com/112396165/188802388-2cda2bf7-e89c-4540-b64a-24dd39f2351c.png)

**Comment by danieleds** [comment]
Hi,

are you using the same code of the guide? Do you get the same error when cloning the code from here? https://github.com/signalwire/guides/tree/main/Video/React-Native-Basic

**Comment by niravcodes** [comment]
Hi, @rushirajStl, 
if you had skipped through the guide, it could be that you're missing the `onRoomReady={(roomSession) => setRoomSession(roomSession)}` line. Another problem might be that the function simply isn't firing (wrong token, or some other error).
